[project]
name = "api"
version = "0.0.1"
description = "API for the mobile app"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "fastapi~=0.119",
    "httpx~=0.28",
    "pydantic~=2.12",
    "pydantic-settings~=2.6",
    "supabase~=2.22",
    "uvicorn~=0.37"
]

[dependency-groups]
dev = []

test = [
    "pytest~=8.4",
    "pytest-asyncio~=1.2",
    "pytest-mock~=3.15",
]
